name: ShounenSumo
version: '${project.version}'
main: net.dmjin.shounensumo.ShounenSumo
api-version: 1.19
authors: [ DMJin ]
description: ShounenSumo plugin
depend: [ProtocolLib]
softdepend: ['Multiverse-Core']
commands:
  arenagenerator:
    description: Pastes the given arena schematic
    aliases: [ ag ]
    permission: shounensumo.admin
    permission-message: &cYou don't have permission to use this command.
    usage: /<command> <arenaName>
    default: true
  sumonpc:
    description: Summons the Sumo NPC
    aliases: [ ssnpc ]
    permission: shounensumo.admin
    permission-message: &cYou don't have permission to use this command.
    usage: /<command>
    default: true
  worldcreator:
    description: Creates the world for the given arena
    aliases: [ wc ]
    permission: shounensumo.admin
    permission-message: &cYou don't have permission to use this command.
    usage: /<command> <parameters>
    default: true